name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set current date as environment variable
        run: echo "DATE=`date +'%Y.%m.%d'`" >>$GITHUB_ENV

      - name: Building TCET Linux Welcome Tar file
        run: |
          cd ..
          tar -czf calamares-desktop.tar.gz calamares-desktop/
          touch checksum
          sha256sum calamares-desktop.tar.gz > checksum
          mv checksum calamares-desktop/
          mv calamares-desktop.tar.gz calamares-desktop/
          
      - name: Delete Previous Latest release
        run: |
          gh release delete latest
      - name: Release Tar File
        run: |
          gh release create ${{ env.DATE }} *tar.gz checksum --title "TCET-Linux Calamares Desktop"
      - name: Release Tar File with latest
        run: |
          gh release create latest *tar.gz checksum --latest --title "TCET-Linux Calamares Desktop"
